### ISSUE TITLE
[🆕]: Aspetti finanziari (I SOLDI)

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#103]
Questa issue viene aperta per poter esprimere il proprio interesse verso l'argomento nel titolo.  

Chiunque sia interessato a questo argomento può mettere un 👍 su questa issue.  

Chiunque tra gli Ambassador sia interessato ad assegnarsi l'argomento per una prima versione può indicarlo in un commento o, più semplicemente, assegnare a se stesso la issue tramite l'interfaccia di GitHub.  

Chiunque sia interessato a contribuire può aggiungere un commento a questa issue.  

Chiunque sia interessato a proporre un argomento alternativo può farlo nella apposita [discussione](https://github.com/Il-Libro-Open-Source/book/discussions/3).  

N.B. Non necessariamente l'argomento sarà trattato in un capitolo a sé stante. Potrebbe essere trattato in un capitolo più ampio o in un capitolo dedicato ad un argomento correlato. Questa issue viene aperta esclusivamente per valutare l'interesse nell'argomento.

**Comment by Developpoo** [comment]
Ieri, parlando con due amici, entrambi sviluppatori (dev), marito e moglie, con due retribuzioni (RAL) diverse, è sorta una domanda: "Perché lei, che ha una RAL di 26.000 euro, guadagna quasi quanto me, che ne guadagno 32.000 euro?"

Abbiamo condotto una breve ricerca per capirne le motivazioni, ed è emerso un ragionamento interessante che spiegherò in breve. Se ritenuto interessante, potremmo approfondirlo sotto diversi aspetti.

Lui guadagna 5.000 euro in più all'anno di lei. Tuttavia, superato lo scaglione dei 28.000 euro, si perdono 100 euro di bonus Renzi. Questo significa che lei riceve il bonus e lui no. Questo solo fatto riduce la differenza tra le loro due buste paga a 1.200 euro. Inoltre, superando i 28.000 euro, lui entra in una fascia di tassazione più alta rispetto a quella di lei, passando dal 25% al 35%. Di conseguenza, i 5.000 euro iniziali di differenza diventano 3.250 euro (5.000 euro - 1.200 euro di bonus Renzi), poi, a seconda di altre differenze, questa cifra può ulteriormente scendere o variare. Fermiamoci qui, poiché questi due parametri sono relativamente stabili e, indipendentemente dalle variazioni nella legislazione, saranno sempre presenti.

In pratica, basandoci su questo ragionamento, è possibile condurre ulteriori riflessioni sulle convenienze di eventuali aumenti o richieste di RAL. Per essere chiari, potrebbe accadere che una persona che guadagna 27.999 euro al mese guadagni effettivamente di più di una che ne guadagna 29.000, e così via. Si può riflettere su come non sempre sia conveniente aumentare la propria RAL da 45.000 a 50.000 euro (gli scaglioni vanno da 28.000 euro in su e poi da 50.000 euro in su). Oppure, si può discutere di come un'azienda possa risparmiare gestendo intelligentemente questi parametri. In sostanza, se il tema vi interessa, si può approfondire ulteriormente. Aspetto volentieri i vostri commenti e le vostre opinioni.

**Comment by sensorario** [comment]
L'argomento e' molto interessante e non solo se si e' dipendenti. Ci sono anche dei casi in cui si puo' essere dipendete (part-time o full-time) ma avere anche una partita iva. Anche in questo caso ci sono delle soglie da rispettare per poter rimanere dentro al regime forfettario, per esempio. Non sono esperto ma penso l'argomento possa essere senza dubbio molto utile.

**Comment by Developpoo** [comment]
Certamente... Tuttavia, se sei titolare di una Partita IVA, è probabile che tu abbia anche un consulente fiscale che, presumibilmente, ti assiste nella preparazione di una valutazione personalizzata della tua situazione. Questo consulente dovrebbe essere in grado di fornirti un quadro su misura che ti aiuti a prendere decisioni adeguate in relazione alla tua situazione specifica.

In linea generale, è importante notare che se percepisci una retribuzione fissa e hai anche un'attività con Partita IVA, dovresti considerare che stai contribuendo all'INPS due volte, il che implica che qualsiasi scelta che fai dovrebbe garantire un vantaggio significativo dal punto di vista finanziario. Ad esempio, il regime forfettario attualmente prevede un limite di 85.000 euro di fatturato annuo, ma è fondamentale valutare se riesci a gestire i tuoi costi in modo tale da rientrare in questo limite e se questa scelta è vantaggiosa per la tua situazione finanziaria complessiva. limite di 85K che è un tetto massimo, non vorrei sbagliare, tra la Ral che hai da dipendente e quanto fatturi ogni anno...

**Comment by Developpoo** [comment]
I contribuenti Forfettari rappresentano un caso a parte in questo contesto. A titolo di completezza, è importante sottolineare che per i primi 3 o 5 anni (la cifra esatta mi sfugge al momento), essi sono soggetti a un'aliquota fiscale del 5%. In seguito a questo periodo iniziale, la loro aliquota fiscale sale al 15%. Queste aliquote si applicano al reddito imponibile, oltre alle obbligatorie contribuzioni INPS. Pertanto, ritengo che questo gruppo possa essere classificato come freelance, ma presenta una dinamica fiscale particolare che richiede un approccio di valutazione altrettanto specifico.

**Comment by Eomm** [comment]
>  Di conseguenza, i 5.000 euro iniziali di differenza diventano 3.250 euro 

2788,14€/anno netti di differenza secondo i miei calcoli spannometrici:

https://docs.google.com/spreadsheets/d/1CH4bL7FOcj70vWBBd8qtiLm1iIoNk0E_/edit?usp=sharing&ouid=100719316011644859154&rtpof=true&sd=true

Comunque si, un calcolatore trasparente che spiega dove finiscono le tasse è formativo ed utile.

Io ho questo molto basic, ma che prende in considerazione l'80% delle cose (pareto style).

**Comment by Developpoo** [comment]
Si è chiaro che è un discorso da vedere in termini generali... io l'ho pensato a cena con amici quindi parlando del più e del meno... il concetto però mi pare una riflessione che nessuno fa o comunque in pochi.. persino io quando parlo di Ral nei vari colloqui ho sempre tirato al rialzo senza effettivamente pensare questo quanto mi cambiava di netto in busta....

comunque il tuo sistema è molto utile... ci sono dei siti che ti calcano lo stipendio medio fatti abbastanza bene..

**Comment by Tonel** [comment]
Da ingegnere informatico iscritto all'albo (uno dei pochi che conosco), secondo me sarebbe molto importante parlare anche dei pro e contro di iscriversi a Inarcassa, magari con un caso di studio con numero e %.

**Pro**:
- Meno tasse
- Pensione vera e (in teoria) sicura (non come INPS)
- ...

**Contro**:
- Minimo da pagare anche se non si fattura
- Non si può scaricare nulla o quasi (spese mediche, edilizie, ...)
- ...

La maggior parte delle persone che ho conosciuto è ingegnere, ma non si iscrive a Inarcassa perchè non ne conosce i benefici.

**Comment by Cadienvan** [comment]
Ciao @Tonel , sicuro potrebbe aver senso tirare dentro la possibilità, chiaramente in maniera unbiased.

**Comment by Developpoo** [comment]
Il settore delle tecnologie dell’informazione e della comunicazione, anche noto con gli acronimi ICT
o TIC, è uno degli ambiti professionali con tassi di crescita a ritmi esponenziali negli ultimi anni,
grazie alla velocità con cui organizzazioni e aziende innovano e, soprattutto, in virtù del processo di
digitalizzazione, che sta toccando ogni settore della società contemporanea. In virtù di questa
evoluzione il settore ad oggi è tra quelli che permettono un più veloce inserimento nel mondo del
lavoro, soprattutto tra i giovani neolaureati, con buoni risultati anche a livello economico,
molteplici le figure professionali ricercate, tra le più richieste sicuramente:

- Amministratore di database;
- Cybersecurity analyst;
- Web developer;
- Software developer;
- Cloud architect;
- Amministratore di sistema;
- IT manager;
- Analista di sistema;
- Tecnico Help Desk;
- etc 

tante figure professionali che permettono anche una discreta scelta nella tipologia di attività da
svolgere in riferimento alle proprie capacità e desideri professionali. Chi si approccia a questo
mondo sicuramente deve avere una propensione di base all’ utilizzo di tutti gli strumenti
informatici nonché una discreta dose di costanza, dedizione e passione. Quindi il primo passo da
compiere per chi si affaccia al mondo dell’ IT e senz’altro la scelta del tipo di lavoro che si intende
svolgere e anche le modalità ovvero se operare in virtù di un contratto di lavoro dipendente o
come sviluppatore freelance, senz’ altro la seconda scelta implica delle difficoltà aggiuntive come
ogni attività imprenditoriale in quanto si devono fronteggiare incertezza e difficoltà economica,
almeno all’ avvio dell’ attività, e ricercare da solo i nuovi clienti nonché scegliere i progetti da
approcciare facendo attenzione che siano calibrati sia alle capacità professionali acquisite nonché
alle dimensioni del progetto stesso. Ovviamente se la scelta di operare come freelance da un
lato porta maggiori difficoltà e responsabilità dall’ altro può condurre chi sceglie questa strada a
importanti risultati sia in termini reddituali ma anche in termini di soddisfazione professionale
poiché sarai libero di organizzare il tuo tempo e scegliere su cosa lavorare tutti aspetti certamente
da non sottovalutare. A conclusione di questa breve introduzione non possiamo far altro che dire
che il primo passo è farti delle domande per capire se questo settore è quello giusto per te e se sì
cosa vuoi ottenere, quindi se hai scelto di entrare in questo ambito professionale leggi il seguito e
ti daremo delle utili informazioni sia che tu ti voglia approcciare con un contratto di lavoro
dipendente o come freelance.

Freelance: prestazione occasionale o partita Iva?

Con la prestazione occasionale si ha la possibilità di testare se stessi da freelance e ad onor del
vero è il principale strumento utilizzati di comincia in quanto di semplice attuazione (basta
emettere una semplice ricevuta). Ma il suo utilizzo è al quanto limitato poichè le norme fiscali
stabiliscono che essa può essere utilizzata solo al ricorrere di due fondamentali requisiti, ovvero:
- quando l’ attività svolta ha il carattere dell’ occasionalità;
- e gli introiti derivanti da tale saltuaria attività non superano i 5,000,00 euro (inteso come importo
lordo e non netto ovvero l’ importo dopo l’ applicazione della ritenuta d’ acconto).
Nel momento in cui l’ attività viene svolta in maniera costante e con l’ impiego di una struttura
maggiormente organizzata e/o superiamo i 5000€ annui in ritenuta d’acconto, allora è obbligatorio
aprire la Partita IVA. Certamente questo secondo passo implica una serie di adempimenti da
svolgere per poter essere pienamente operativi, ovviamente ti consigliamo di affidarti ad un
professionista che possa consigliarti e indirizzarti su i vari step da seguire in base alla normativa
fiscale per iniziare ma anche per gestire negli anni a venire la tua attività. Nonostante questo
consiglio comunque trattiamo qui di seguito la normativa di base in modo da poter avere idea di
quello che dovrai fare e di come farlo. I primi passi da compiere in questo senso sono
principalmente tre:

1. Definire il regime fiscale
2. Individuare il codice ATECO
3. Iscrizione alla cassa previdenziale

Per quanto riguarda la definizione del regime fiscale chi apre la partita iva può scegliere tra
semplificato, ordinario e forfettario, ciascuno è stato pensato per determinate categorie di
contribuenti e caratterizzato da aspetti più o meno vantaggiosi, ma la scelta tra questi è senz’ altro
dettata in primo luogo dal volume d’ affari che si pensa possa avere l’ attività infatti il regime
forfettario può essere applicato solo fino ad un massimo di ricavi pari ad 85,000 euro, il regime
semplificato fino ad una soglia di ricavi di 500,000 euro oltre il quale si applica il regime ordinario.
Facciamo qualche considerazione sul regime forfettario e semplificato/ordinario, le caratteristiche
fondamentali sono nel primo il fatto che i costi sostenuti per lo svolgimento dell’ attività non sono
deducibili in quanto il reddito prodotto è soggetto ad imposta sostitutiva, pari al 5% per i primi
cinque anni di attività e successivamente al 15%, mentre nel secondo se da un lato vi è la
possibilità di dedurre tutti i costi inerenti dall’ altro si soggiace alla tassazione a scaglioni irpef ben
più salata (si parte infatti con un’ aliquota del 23% su redditi fino a 15,000 euro). Quindi
considerando che l’ attività che ci si appresta a svolgere è tipicamente caratterizzata da costi di
produzione bassi ci si dovrebbe indirizzare verso il regime forfettario, il quale peraltro prevede:
- la non imponibilità ai fini iva dei compensi, cosa che gioca senz’ altro un importante vantaggio
strategico perché, a certe condizioni, potresti risultare maggiormente competitivo rispetto a
colleghi che invece aderiscono a diversi regimi fiscali che prevedono l’ applicazione dell’ imposta;
- e la non applicazione della ritenuta d’ acconto a titolo d’ acconto sui compensi, cosa che di fatto
comporta che al momento dell’ incasso il cliente trattiene la somma del 20% della fattura, che
successivamente verserà allo stato e che per te sarà come una sorta di acconto anticipato sulle
eventuali tasse che liquiderai nella dichiarazione dei redditi dell’ anno di riferimento.
Ovviamente le considerazioni sopra esposte non sono sempre valide per tutti, vanno affrontate
anche tenendo presenti la situazione personale, sia per le presenza di eventuali cause ostative che
potrebbero rendere inapplicabile il regime forfettario, ma anche perché se da un lato presenta
senz’ altro dei vantaggi dall’ altro preclude, essendo il reddito prodotto soggetto a tassazione
separata, all’ accesso a qualsiasi tipo di detrazione fiscale, quindi il consiglio è sicuramente quello
di svolgere un’ attenta analisi di costi / benefici prima di scegliere un regime piuttosto che un’ altro.
Una volta individuato il regime fiscale più appropriato per le proprie esigenze, il secondo passo e
senza dubbio quello di individuare il codice ATECO di riferimento, si tratta di una combinazione
alfanumerica che identifica un’ attività economica, esso è necessario per l’ apertura della partita
iva in quanto va inserito insieme ai dati personali nel modello AA9/12 comunicato all’ Agenzia delle
entrate, e l’ individuazione del giusto codice è essenziale affinché ciascuna attività sia classificata in
modo standardizzato ai fini fiscali, contributivi e statistici. Considerato che il mondo dell’ IT
racchiude al suo interno una molteplicità di attività che possono essere svolte, elenchiamo di
seguito le macro categorie nell’ ambito delle quali va ricercato il codice ATECO più rispondente all’
attività che si intende svolgere:

62.0 - PRODUZIONE DI SOFTWARE, CONSULENZA INFORMATICA E ATTIVITÀ CONNESSE
62.01 Produzione di software non connesso all'edizione
62.02 Consulenza nel settore delle tecnologie dell'informatica
62.03 Gestione di strutture informatizzate
62.09 Altre attività dei servizi connessi alle tecnologie dell'informatica

Come potete già notare, bisogna in primo luogo identificare la macro categoria all’ interno della
quale si andrà ad operare più verosimilmente, e all’ interno di essa andare ad identificare poi il singolo ATECO maggiormente rispondente. Questa scelta è assolutamente importante e da non sottovalutare, poiché se vuoi aprire la Partita IVA come sviluppatore web, dovrai farlo in modo diverso
se:
• lavori come semplice programmatore: apri come libero professionista
• vendi sul tuo sito web applicazioni, applicativi, software scaricabili: apri come ditta individuale
La scelta è molto importante in quanto porta con se una serie di implicazioni sia in sede di apertura
della partita iva che ai fini previdenziali, e nello specifico se opererai come libero professionista all’
atto dell’ apertura della partita iva sarà sufficiente richiedere il numero della partita iva all’ Agenzia
delle entrate, mentre nel secondo caso andrà curata anche l’ iscrizione alla CCIAA territorialmente
competente e Inail. Ancor più interessante l’ aspetto previdenziale in quanto:
- il libero professionista, in mancanza di una cassa di riferimento, andrà iscritto in gestione separata INPS il che significa che pagherai i contributi solo in sede di liquidazione annuale delle imposte
con un aliquote del 26,23% per il 2023 sul reddito prodotto;
- il titolare di ditta individuale, andrà invece iscritto alla gestione artigiani e commercianti la quale
prevede il versamento dei c.d. contributi fissi che ammontano a circa 1,000 euro da versare a cadenza trimestrale (16/05 – 20/ 08- 16/11 – 16/02). e i cd. Contributi a percentuale eccedente il
reddito minimale ( 17,504 euro per il 2023) da calcolare e versare in sede di dichiarazione annuale.
Come avrai avuto modo di comprendere quindi si tratta di una scelta dalle molteplici implicazioni,
che peraltro la nostra trattazione non ha la presunzione di sviscerare nel complesso ma semplicemente nei concetti di base

Contratto di lavoro dipendente
Trattiamo adesso anche il caso si decida di approcciarsi al mondo dell’ IT ricercando un’ impiego
con contratto di lavoro dipendente, in questo caso sono molteplici i contratti che potrebbero essere applicati e la cui trattazione non si può esaurire con poche e brevi nozioni, diciamo che in virtù
di ciò preferisco dare dei suggerimenti di ordine pratico. Anzitutto nel momento in cui ti viene proposto un contratto bisogna analizzare il CCNL di riferimento, qualifica, livello, conoscendo questi
dati potrai facilmente identificare la mansione che effettivamente sarai chiamato a svolgere nonché la retribuzione associata. Molto spesso il CCNL proposto è quello Commercio/terziario PD e
per questo di seguito esemplifico gli aspetti salienti che lo contraddistinguono:

ISTITUTI CONTENUTI
Periodo di prova Art.2
Quadri e primo livello: 6 mesi. Altri livelli: 3 mesi.
I periodi di prova indicati per i rispettivi livelli devono intendersi di effettivo lavoro.
Per i contratti a termine la durata del periodo di prova non potrà essere superiore al 50% della durata del contratto di lavoro.

40 ore settimanali suddivise di norma in cinque giornate per la generalità dei lavoratori, 38 per i dipendenti da aziende che si occupano di vendita al pubblico nei magazzini a prezzo unico, ipermercati, grandi magazzini, supermercati alimentari e cash and carry, 42 ore per i dipendenti da aziende distributrici di carburante metano compresso per autotrazione, 45 per i dipendenti da gestori di impianti di distribuzione carburanti. Per i dipendenti da gestori di impianti di distribuzione di carburante esclusivamente autostradali l’orario di lavoro è fissato in 40 ore settimanali.
Possibilità di adottare orari flessibili per un massimo di 48 ore settimanali ripartiti su 6 giorni, ad esclusione

Orario di lavoro Art. 7 e ss delle fattispecie elencate nel CCNL, e articolazione multiperiodale dell’orario di lavoro con modalità da definire a livello di contrattazione aziendale.

Banca delle ore Art. 10 
Tutte le tipologie di lavoro straordinario potranno confluire nel monte ore della Banca delle Ore nella misura del 100%.

Straordinario, Notturno, Festivo Artt. 12/13
Max. 250 ore annue di lavoro straordinario per lavoratore.

a. lavoro straordinario diurno (dalla 41a alla 48a ora settimanale) 15%
b. lavoro straordinario diurno (eccedenti la 48a ora settimanale) 20%
c. lavoro straordinario notturno esclusi i turni regolari di servizio (dalle ore 22 alle ore 6) 50%
d. lavoro straordinario festivo e di domenica 30%

È considerato lavoro notturno quello prestato tra le 22.00 e le 6.00.
Le ore di lavoro notturno sono retribuite con la retribuzione oraria maggiorata del 15%.

Maggiorazione riposi settimanali Art. 14
Le ore di lavoro prestate nei giorni di riposo settimanale di cui alla Legge n.370/1934 dovranno essere retribuite con le maggiorazioni previste dall’art. 12 da considerarsi omnicomprensive e non cumulabili.

Ferie e permessi Art. 15/19
Ferie annuali: 4 settimane. Ex festività: 32 ore di permessi retribuiti annui.

Retribuzione Art.25
Paga giornaliera: divisore pari a 26; quota oraria di retribuzione: divisore pari a per “164” per il personale con orario normale di trentotto ore settimanali, “168” per il personale con orario normale di quaranta ore settimanali, “182” per il personale con orario normale di quarantadue ore settimanali e “195” per il personale con orario normale di quarantacinque ore settimanali.
In caso di assunzione di un lavoratore a tempo indeterminato da adibire allo svolgimento di mansioni rientranti nei livelli dal 2° al 6°, qualora quest’ultimo abbia un’esperienza professionale pregressa inferiore ai 5 anni nelle attività per le quali viene impiegato, al datore di lavoro è riconosciuta la facoltà di assumere il suddetto lavoratore riconoscendogli, per i primi due anni, le “retribuzioni di primo ingresso”, ridotte rispetto al livello ordinario di inquadramento pari al 7,5% per il primo anno e 5% per il secondo. 
Le suddette riduzioni retributive possono essere applicate anche dalle aziende di nuova costituzione o
in fase di avvio di una nuova attività e per un massimo di due anni, indipendentemente dal livello di
inquadramento.

Contratto di reinserimento Art. 25 bis
A tempo determinato o indeterminato è applicabile ai lavoratori di prima assunzione nel settore di
appartenenza dell'azienda con l’obiettivo di favorire il reinserimento lavorativo e a condizione che non
abbiano già svolto le stesse mansioni, che abbiano più di 35 anni di età, e che si trovino in condizione
di disoccupazione o sospensione, alla ricerca di nuova occupazione, o che abbiano cessato un'attività
autonoma. Durante i primi 24 mesi, le retribuzioni ridotte rispetto livello ordinario di inquadramento
saranno così determinate:

- prima metà del periodo: 85%;
- seconda metà del periodo: 90%.

Ogni singola azienda può stipulare un solo contratto a tempo indeterminato; la stipula di un successivo
contratto è consentita solo nel caso in cui il precedente contratto sia stato stabilizzato con il superamento del periodo di prova.
In caso di assunzioni a tempo determinato le aziende potranno stipulare:

 n. 2 contratti da 0 a 5 dipendenti;
 n. 3 contratti con più di 5 dipendenti.

Una tantum Art. 25 ter
Erogata a favore dei soli lavoratori in forza alla data di stipula del presente CCNL.
Tale importo verrà erogato pro quota in rapporto ai mesi di anzianità di servizio maturata nel periodo gennaio 2020 – dicembre 2022 e verrà riproporzionato in caso di part time.

Importi una tantum
Livello 01/02/2023
Q € 500,00
1° € 450,00
2° € 400,00
3° € 350,00
4° € 300,00
5° € 250,00
6° € 200,00
7° € 170,00
Operatori di vendita
Categoria 01/02/2023
Categoria 1 € 270,00
Categoria 2 € 220,00

Mensilità Quattordici.

Premio risultato Art. 30 Potrà essere negoziato in sede aziendale ponendo particolare attenzione all’attivazione di programmi di welfare.

Scatto di merito Art. 31 Definito con accordo aziendale in funzione del raggiungimento di parametri oggettivi legati al merito o alla professionalizzazione dei singoli lavoratori.

Malattia Artt. 36 e ss
Conservazione del posto:
180 Nell’arco di 1 anno solare per malattia continuativa certificata
GG Nell’arco di 36 mesi sommando + eventi
720 Nell’arco temporale di 48 mesi in caso di malattie di particolare GG gravità.
60% dal 1° al 3° gg/max 4 eventi

INTEGRAZIONE 75% dal 4° al 45° gg
Massimo 45 gg di integrazione/anno
Patologie gravi: integrazione del 100% per massimo 180 gg/anno

Infortunio Art. 38
Trattamento economico:

- il 100% il giorno dell’infortunio;
- il 60% per i successivi tre giorni di carenza;
- il 90% dal 5° al 20° giorno;
- il 100% della normale retribuzione per i giorni dal 21° al 180° giorno.

Part time Art.76 e ss 
 Maggiorazione del 10% per ore in regime di clausole elastiche.
 Maggiorazione del 10% per le ore supplementari.

Lavoro intermittente Art.86 e ss
Indennità di disponibilità pari al 20% della retribuzione del livello di riferimento. Nessun compenso in caso di malattia o altro evento che renda impossibile rispondere alla chiamata. Qualora l’evento di malattia si verifichi durante la chiamata, il lavoratore avrà diritto ad una integrazione dell’indennità eventualmente erogata dall’INPS fino al raggiungimento del 20% della retribuzione lorda contrattualmente prevista per tutta la durata della chiamata

Tempo determinato Art.92 e ss
Limiti numerici: 50% dei lavoratori a tempo indeterminato, apprendisti e assunti con contratto di reinserimento in forza al momento dell’assunzione. Salvo ogni diverso accordo sindacale aziendale. Resta salva la facoltà di assumere con contratto a tempo determinato n. 3 dipendente nelle singole unità produttive con in forza fino a 5 dipendenti come sopra conteggiati.

Somministrazione Art. 100 e ss 
Contemporaneamente lavoratori somministrati a tempo determinato in misura non superiore al 20% annuo dei lavoratori dipendenti a tempo indeterminato in servizio.

LAVORO A DISTANZA Telelavoro Lavoro agile (smart working) Art.106 e ss
Il lavoro a distanza, salvo eventi eccezionali, ha carattere volontario sia per l’azienda sia per il lavoratore
dipendente e può svolgersi anche con contratto part-time o a tempo determinato. Tutelato il diritto alla disconnessione

Generalmente quando ci si approccia per la prima volta alla ricerca di un posto di lavoro
nell’ ambito dell’ IT, come in altri casi, sarà maggiormente probabile inserirsi con dei livelli più bassi che comunque prevedono delle RAL interessanti, ma come molto spesso
non accade in molti altri settori, le probabilità di crescita sia professionale che reddituale
sono elevate, non di rado accade infatti che dopo pochi mesi si possa ricercare con successo nuovi impieghi con proposte economiche in crescita, proporzionate alle esperienze
fatte. Sicuramente quindi un ambito in cui, anche le ambizioni di crescita e successo
personale, possono trovare spazio. Il consiglio è quello di non soffermarsi, almeno all’
inizio, sul solo aspetto reddituale ma anche su cosa apprenderei con il tuo lavoro, poiché
il bagaglio di esperienze pregresse in quest’ ambito hanno sicuramente un peso importante nella ricerca di un impiego futuro. Sicuramente, i principali aspetti positivi dell’ essere
inquadrato come lavoratore dipendente sono le tutele e i diritti che vengono riconosciuti, il fatto di non doversi preoccupare continuamente di andare sul mercato alla ricerca
di clienti e comunque sapere che terminato il mese di lavoro hai la certezza di ricevere
un importo (la Ral) già noto a priori.

Conclusioni
In breve se hai scelto di affacciarti al mondo dell’ IT, hai deciso di entrare in un settore
fortemente in espansione, che al momento risulta essere tra i migliori in termini di occasioni lavorative, sia che tu scelga di approciarti come freelance che come lavoratore
dipendente, il consiglio è quello di impegnarti e apprendere quando più possibile e calibrare la tua attività in base alle skills che con il tempo acquisirai, infatti l’ aspetto forse
più interessante sono le infinite possibilità che il settore ti offre sia nella scelta di ciò
che vuoi fare, perché se scegli un lavoro che ti piace sei già a metà dell’ opera, sia di come farlo, potrai crescere umanamente insieme alla tua attività

**Comment by Cadienvan** [comment]
Ciao @Developpoo se hai bisogno di aiuto per buttare giù il markdown sentiamoci!

**Comment by Developpoo** [comment]
Michael perdonatemi ma sono incasinatissimo spero di riuscire la settimana
prossima

Il giorno sab 13 gen 2024 alle ore 09:07 Michael Di Prisco <
***@***.***> ha scritto:

**Comment by Cadienvan** [comment]
Tranquillo Alessio,
era solo per propormi di aiutarti, nessuna fretta!
