### ISSUE TITLE
Primi passi: Come scrivere i primi contenuti

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#108]
Ci siamo.
La prima riunione è andata, gli argomenti sono al vaglio, ma ora dobbiamo organizzarci su come cominciare a buttare giù i primi contenuti.

Dico la mia e apro le danze per parlarne tutti assieme:
Dobbiamo stabilire delle linee guida di scrittura (Qui credo che @serenasensini potrà darci una mano visto che ha esperienza a riguardo ed è un tema che ho sentito nominare da lei parecchie volte), gender neutrality (O perlomeno evitare "insulti indiretti") e metodo di stesura.  

Dopodiché possiamo buttare giù in maniera totalmente libera dei contenuti su argomenti ai quali ci siamo assegnati (Stiamo ancora definendo - #53 - le modalità), ma direi che potremmo partire con la creazione di un branch che parte da main e buttare giù dei contenuti in un'apposita cartella chiamata con lo slug dell'argomento (Es. `docs/arrchitetture-software/README.md`), si fa sempre in tempo a ribasarli e spostarli se cambiamo flow.  
> Per questo stabilirei come deadline metà Ottobre, diciamo Domenica 15, di modo che per l'eventuale presenza / presentazione al Codemotion si abbia qualche contenuto qualora la community volesse cominciare a darci un occhio.

Una volta buttate giù due righe ne parliamo tutti assieme per capire se ci siamo a livello di linee guida e stesura, ci calibriamo e ci diamo una deadline per la chiusura della prima "in brutta" degli argomenti.
> Per questo direi come deadline il mese successivo, diciamo Domenica 19 Novembre.

Nel frattempo raccogliamo feedback in base a come vanno le cose!

**Comment by Cadienvan** [comment]
Per completezza d'informazione: Nel canale Telegram degli Ambassador si sta discutendo del metodo di branching e le prime PR sono già partite proponendo i primi contenuti.

**Comment by Cadienvan** [comment]
@Il-Libro-Open-Source/ambassadors che dite, chiudiamo? Direi che le linee guida e i primi passi li stiamo già facendo eccome!

**Comment by corradopetrelli** [comment]
Confermo
