### ISSUE TITLE
Feedback: Il titolo del libro

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#109]
Apro questa discussione che potrebbe anche restare aperta per mesi, perché vorrei raccogliere feedback sul possibile nome che potrebbe avere il libro.

La mia proposta, che credo essere molto in linea con temi scelti e argomenti trattati, è:
**Guida Galattica Per Developer**

Scatenatevi.

**Comment by guizzo** [comment]
A me **Guida galattica per sviluppatori** piace molto 👍

**Comment by eppak** [comment]
Io aggiungo "Atlante informatico per sviluppatori", anche qualcosa con "Cartografo dello sviluppo"

**Comment by guizzo** [comment]
Anche una roba **LIKE** _La Bussola Del Dev: orientarsi nel mondo dello sviluppo_

**Comment by Saleiux** [comment]
a me è venuto in mente "La bibbia del dev!" "Tutto ciò che devi sapere per ...."  e tipo mettere un falso mito che esiste sugli sviluppatori o comunque qualcosa di divertente che attiri l'attenzione! Per esempio guardando il profilo di Michael "La bibbia del dev!" "Tutto ciò che devi sapere per diventare il terrore dei recruiter!" Non so se può essere un'idea!

**Comment by guizzo** [comment]
> a me è venuto in mente "La bibbia del dev!" "Tutto ciò che devi sapere per ...."  e tipo mettere un falso mito che esiste sugli sviluppatori o comunque qualcosa di divertente che attiri l'attenzione! Per esempio guardando il profilo di Michael "La bibbia del dev!" "Tutto ciò che devi sapere per diventare il terrore dei recruiter!" Non so se può essere un'idea!

Intendi una roba tipo: "La Bibbia del dev: perché Java e Javascript sono la stessa cosa"? 😂

**Comment by Saleiux** [comment]
> > a me è venuto in mente "La bibbia del dev!" "Tutto ciò che devi sapere per ...."  e tipo mettere un falso mito che esiste sugli sviluppatori o comunque qualcosa di divertente che attiri l'attenzione! Per esempio guardando il profilo di Michael "La bibbia del dev!" "Tutto ciò che devi sapere per diventare il terrore dei recruiter!" Non so se può essere un'idea!
> 
> Intendi una roba tipo: "La Bibbia del dev: perché Java e Javascript sono la stessa cosa"? 😂

ahahah si qualcosa del genere! però forse così per chi è proprio agli inizi può confondere le idee ahahah

**Comment by sistella** [comment]
Dev si `<div>`enta

**Comment by mirkodeglinnocenti** [comment]
L'Enciclopedia dello Sviluppatore: Una guida completa per Dev

**Comment by halfpass25** [comment]
Propongo “Il manuale del DevelOpen” e per la versione internazionale, “The DevelOpen Reference Handbook” 📝

**Comment by Developpoo** [comment]
<DEV> in cerca d'autore

**Comment by Developpoo** [comment]
direi di raccogliere tutte le idee e poi fare un bel sondaggio

**Comment by JeyDi** [comment]
Faccio un upvote su **Guida Galattica Per Sviluppatori** perchè penso che racchiuda proprio tutto il senso del progetto :)

**Comment by rrhinox** [comment]
Dopo aver letto tutti i capitoli, propongo questi in ordine di serietà : 

1. ### ENG | "The whole life (cycle) of a Developer - the right way!" 
   ### ITA | "Tutta la vita di uno Sviluppatore - la giusta via!" (o la via maestra che magari suona meglio boh io la butto lì!)

2. ### ENG | "The Developer's Handbook - toward opensource and beyond!"
   ### ITA | "Il Manuale dello Sviluppatore - verso l'OpenSource e oltre!"

3. ### ENG | "Dev life - how to survive and make it to retirement with real money!"
   ### ITA | "Vita da Dev - come sopravvivere e arrivare alla pensione coi soldi veri!" 😄 (quì chiedendo aiuto a @GuidoPenta ovviamente!)

P.S. In ogni caso : _Guida Galattica Per Sviluppatori_ molto "snello" e figo!

**Comment by GuidoPenta** [comment]
Il libro Open Source
(con sottotitolo): ovvero, come centrare un div

**Comment by rosariospalla** [comment]
Ho abbozzato qualche nome:

1. Developer mode
2. Mi trasformo in un developer
3. Super developer _e sottotitolo_
4. Ricetta per il developer perfetto
5. Developer stellato
6. Il calcolatore nelle mani giuste?
7. L'uomo che sussurrava ai bit
8. Bit Generation
9. Compendium 

In caso votata con un commento che indica l'indice del titolo. Tutto dipende da taglio ironico, e di che tipo, o meno che si vuole dare.
Siate clementi.

**Comment by Cadienvan** [comment]
"Bit Generation" non mi spiace ahah grazie mille per i suggerimenti @rosariospalla !!

**Comment by EMCestari** [comment]
Io quoto Guido: ormai questo è "IL LIBRO OPEN SOURCE". Poi magari ci mettiamo un sottotitolo :)
