### ISSUE TITLE
RAL vale la pena puntare a rialzo?

### ISSUE THREAD

**Issue by Developpoo** [Il-Libro-Open-Source/book#136]
Ieri, parlando con due amici, entrambi sviluppatori (dev), marito e moglie, con due retribuzioni (RAL) diverse, è sorta una domanda: "Perché lei, che ha una RAL di 26.000 euro, guadagna quasi quanto me, che ne guadagno 32.000 euro?"

Abbiamo condotto una breve ricerca per capirne le motivazioni, ed è emerso un ragionamento interessante che spiegherò in breve. Se ritenuto interessante, potremmo approfondirlo sotto diversi aspetti.

Lui guadagna 5.000 euro in più all'anno di lei. Tuttavia, superato lo scaglione dei 28.000 euro, si perdono 100 euro di bonus Renzi. Questo significa che lei riceve il bonus e lui no. Questo solo fatto riduce la differenza tra le loro due buste paga a 1.200 euro. Inoltre, superando i 28.000 euro, lui entra in una fascia di tassazione più alta rispetto a quella di lei, passando dal 25% al 35%. Di conseguenza, i 5.000 euro iniziali di differenza diventano 3.250 euro (5.000 euro - 1.200 euro di bonus Renzi), poi, a seconda di altre differenze, questa cifra può ulteriormente scendere o variare. Fermiamoci qui, poiché questi due parametri sono relativamente stabili e, indipendentemente dalle variazioni nella legislazione, saranno sempre presenti.

In pratica, basandoci su questo ragionamento, è possibile condurre ulteriori riflessioni sulle convenienze di eventuali aumenti o richieste di RAL. Per essere chiari, potrebbe accadere che una persona che guadagna 27.999 euro al mese guadagni effettivamente di più di una che ne guadagna 29.000, e così via. Si può riflettere su come non sempre sia conveniente aumentare la propria RAL da 45.000 a 50.000 euro (gli scaglioni vanno da 28.000 euro in su e poi da 50.000 euro in su). Oppure, si può discutere di come un'azienda possa risparmiare gestendo intelligentemente questi parametri. In sostanza, se il tema vi interessa, si può approfondire ulteriormente. Aspetto volentieri i vostri commenti e le vostre opinioni.

**Comment by Cadienvan** [comment]
Ciao @Developpoo , come ti accennavo su LinkedIn credo che la cosa possa rientrare nel già accennato argomento "soldi" (#103 ), che ne dici? Nel caso riporta lì il tuo commento, assegnati la issue (Così sappiamo che te ne occuperai tu) e da lì raccogliamo feedback unificati, che ne pensi?

**Comment by Developpoo** [comment]
si assolutamente... cancella pure questo messaggio...
