### ISSUE TITLE
chore: link a github pages

### ISSUE THREAD

**Issue by Eomm** [Il-Libro-Open-Source/book#143]
Ciao,
nella home del repository:

<img width="414" alt="image" src="https://github.com/Il-Libro-Open-Source/book/assets/11404065/05a610c2-2938-4543-ae5c-de798eda5af6">

è molto utile aggiungere:

- link diretto al sito: https://il-libro-open-source.github.io/book/
- topic per esser trovati nelle ricerche di GH

Esempio della console di modifica (ingranaggio vicino ad `About`)

<img width="657" alt="image" src="https://github.com/Il-Libro-Open-Source/book/assets/11404065/324ba303-ea50-4af1-ac7d-e33ad61d0f1a">

**Comment by Cadienvan** [comment]
Grazie Manuel, ottimi spunti come sempre!
Qualcosina al volo ho fatto, mi ero perso nel tempo.

L'unica cosa che non trovo è la lingua del progetto. Come faccio ad indicare che è un progetto italiano?

**Comment by Eomm** [comment]
> Come faccio ad indicare che è un progetto italiano?

Non credo esista questa impostazione - ho sempre visto un menu nella prima pagina al massimo (es: https://github.com/goldbergyoni/javascript-testing-best-practices#translations---read-in-your-own-language )

**Comment by Cadienvan** [comment]
Allora sarà una supposizione di Github perché se per esempio vai a cercare nei trending repo c'è lo spoken language.

Grazie ancora per il contributo :D
