### ISSUE TITLE
Allinea issues dei nuovi capitoli con l'issue template 

### ISSUE THREAD

**Issue by corradopetrelli** [Il-Libro-Open-Source/book#144]
### Descrizione

Per poter triggerare l'automatismo è fondamentale modificare la struttura delle issue finora create per la creazione dei nuovi capitoli.

I seguenti step devono essere svolti:
- [x] Aggiungere la label `nuovo-capitolo`
- [x] Modificare la struttura del titolo con`[🆕]: NOME_DEL_CAPITOLO`
- [ ] Modificare la struttura del corpo del testo con la struttura delle issue template
- [ ] Verificare se qualcuno ha già lavorato su quel capitolo e chiedergli di modificare il nome del branch con `add/nome-del-capitolo`

Sfortunatamente sarà una cosa che dovrò fare a mano ed influirà solo Github e non il codice contenuto nel repository per tale motivo la issue verrà semplicemente chiusa quando tutte le tasks verranno ultimate.

**Comment by Cadienvan** [comment]
@corradopetrelli se riesci a farlo per una issue e me la linki provo a pensarci io tra oggi e sabato.

**Comment by corradopetrelli** [comment]
@Cadienvan prima bisogna chiudere #142

**Comment by corradopetrelli** [comment]
Per risolvere il problema che qualcuno si ritrova con i branch con nomi diversi rispetto allo standard ed evitare di farlo a manina noi da github ho fatto uno script bash che fa questo.
Per il futuro naturalmente lo script non servirà ma è solo per fare una "migrazione distribuita".
Chiedo anche a @kasuken se può verificarne la validità (scusami se ti butto dentro).

Basta:
- Diassegnarsi la issue e riassegnarsela triggerando così `create-issue-branch` per la creazione secondo lo standard
- Inserire nella variabile `vecchio_nome` il nome del branch che si ha su local
- Inserire nella variabile `nuovo_nome` il nome del branch che ha creato `create-issue-branch`

Lo script bash è il seguente:
```bash
#!/bin/bash
remote="https://github.com/Il-Libro-Open-Source/book.git"
vecchio_nome="INSERISCI_NUOVO_VECCHIO_BRANCH"
nuovo_nome="INSERISCI_NUOVO_NOME_BRANCH"

# Posizionati sul branch
git checkout $vecchio_nome
# Allineati con il branch remoto
git pull $vecchio_nome
# Rinomina il branch con il nuovo nome
git branch -m $vecchio_nome $nuovo_nome
# Cancella il vecchio branch su remote
git push $remote --delete $vecchio_nome
# Fai sì che git non usi più il vecchio nome quando pushi
git branch --unset-upstream $nuovo_nome
# Pusha il branch con il nuovo nome su remote
git push $remote $nuovo_nome
#  Reimposta il branch upstream per il ramo locale nuovo nome
git push $remote -u $nuovo_nome
```

**Comment by corradopetrelli** [comment]
@Cadienvan va benissimo
