### ISSUE TITLE
[🆕]: Protocolli di comunicazione

### ISSUE THREAD

**Issue by allevo** [Il-Libro-Open-Source/book#153]
# 🆕 Nuovo capitolo - Protocolli di comunicazione

## Descrizione

Vorrei dividere il capitolo in 2 sottosezioni:
- protocolli di comunicazione:
  - TCP/UDP
  - HTTP (1, 2, 3)
  - DNS

- Rappresentazione di dati (da rinominare):
   - testuale
     - text plain 
     - JSON (esempio di rest API / configurazioni etc...)
     -  XML (esempio SOAP)
   - binario (avro, msgpack, gRPC)

Vorrei provare a non essere così noioso come l'argomento potrebbe sembrare poiché lo ritengo molto importante.
Inoltre non vorrei andare troppo approfondito altrimenti verrebbe troppo lungo.

Prima di scrivere effettivamente il testo del capitolo, metterò dei link in questa issue in modo da collezionare una serie di informazioni. Poi proseguire effettivamente poi con la scrittura.

Qualsiasi input è il benvenuto.

## Fonti

Lista da stilare durante la scrittura del capitolo.

**Comment by Cadienvan** [comment]
@allevo credo tu ci abbia già pensato ma farei comunque notare che questi sono protocolli standard che, volendo, uno può ignorare anche se è un Anti pattern.. cioè nessuno mi vieta di mandare un testo e leggerlo senza alcun formato dietro

**Comment by BrianAtzori** [comment]
Ciao @allevo ! Questo capitolo è molto interessante, in questo periodo mi sono sganciato un po' perchè per tutti sono settimane full ma mi piacerebbe darti un feedback se possibile quando butti giù qualcosa, se serve anche un mano! 

Lo dico per il semplice fatto che per la maggior parte della mia carriera sono stato principalmente un sistemista quindi ne mastico un pochino e mi è capitato spesso di trovare dev navigat* che non avevano chiaro il concetto di protocollo e di conseguenza HTTP e DNS rimanevano delle semplici sigle

Se può far piacere il mio contributo, taggami pure ☺️

**Comment by Cadienvan** [comment]
@BrianAtzori che ne pensi di assegnarti il capitolo così da "ufficializzare" il supporto alla stesura?

**Comment by allevo** [comment]
Ciao @BrianAtzori ! io non sono un esperto, ma solo un impallinato di ste cose. Un occhio attento ed esperto decisamente farebbe comodo!
Possiamo procedere in diversi modi:
- quello suggerito sopra
- scrivere qui qualche pezzo di testo che vorresti inserire
- mandare link che danno informazioni o una vista particolare dell'argomento.
Per me non c'è nessun problema, da ambassador sono qui di supporto / scrittura / commento / mettere citazioni / (metti quello che vuoi!).

La traccia che vorrei seguire è quella scritta in alto (ma sempre modificabile se lo riteniamo lecito). Su quali argomenti vuoi incominciare?

**Comment by BrianAtzori** [comment]
> @BrianAtzori che ne pensi di assegnarti il capitolo così da "ufficializzare" il supporto alla stesura?

Hai ragione anche tu, ora provvedo!

**Comment by BrianAtzori** [comment]
> Ciao @BrianAtzori ! io non sono un esperto, ma solo un impallinato di ste cose. Un occhio attento ed esperto decisamente farebbe comodo! Possiamo procedere in diversi modi:
> 
> * quello suggerito sopra
> * scrivere qui qualche pezzo di testo che vorresti inserire
> * mandare link che danno informazioni o una vista particolare dell'argomento.
>   Per me non c'è nessun problema, da ambassador sono qui di supporto / scrittura / commento / mettere citazioni / (metti quello che vuoi!).
> 
> La traccia che vorrei seguire è quella scritta in alto (ma sempre modificabile se lo riteniamo lecito). Su quali argomenti vuoi incominciare?

Secondo me come traccia ci può stare! Espanderei solo la prima parte, dandogli un'introduzione che parli di protocollo, ho in mente un paio di risorse a cui attingere, paragrafi di libri, che possono dare spunti interessanti per rendere il pezzo accattivante e non troppo pesante. Ovviamente non copiando ma rielaborando!

Da lì proseguirei con la struttura che hai impostato tu che mi sembra ottima, magari rifaccio una pensata sui protocolli che potrebbero interessare per arricchire la prima parte!

Diciamo che io mi sento meno esperto sulla parte di dati, quindi se ti va potremmo suddividerci i topic lasciando a me la parte di protocolli e a te la parte di dati e poi "reviewarci" a vicenda con il supporto del gruppo, che dici? 

Se ti sembra un buon approccio in settimana rifaccio una pensata e prossimamente inizio a buttare giù i contenuti ☺️ 🚀

**Comment by BrianAtzori** [comment]
Per mantenere traccia delle attività, ho girato ad @allevo in privato una bozza di introduzione, prossimamente potremmo avere una prima traccia di capitolo!

**Comment by Cadienvan** [comment]
@allevo @BrianAtzori un uccellino mi ha detto che qualcosa state scrivendo 👀

**Comment by BrianAtzori** [comment]
> @allevo @BrianAtzori un uccellino mi ha detto che qualcosa state scrivendo 👀

Yep come hai potuto vedere abbiamo buttato giù qualcosa che andava solo pushato, rispetto a quanto ci siamo detti ieri tutti insieme sul gruppo ci sentiremo poi io e Tommaso per aggiungere i protocolli ed eventuali altre cose che potrebbero emergere 💪🏻
