### ISSUE TITLE
Aggiungere riferimenti ad altri IDE nel CONTRIBUTING

### ISSUE THREAD

**Issue by nicolaerario** [Il-Libro-Open-Source/book#158]
Come suggerito [qui](https://github.com/Il-Libro-Open-Source/book/pull/149#pullrequestreview-1704282409), sarebbe carino aggiungere dei riferimenti agli altri editor oltre che a `vscode`

**Comment by Cadienvan** [comment]
Lo farei volentieri ma lavorando da una vita su VS Code non ho esperienze su altri IDE.
