### ISSUE TITLE
il comando format:check non funziona su Windows

### ISSUE THREAD

**Issue by Livio74** [Il-Libro-Open-Source/book#174]
Ciao a tutti,

nel file CONTRIBUTING.md volevo segnalare che se lavoro su Windows il comando npm run format:check (e anche write) non funziona, bisogna lanciarlo da riga di comando così:

```cmd
npx prettier --check '**\*.md'
```
questo perché il comando è unix style , non so se in generale con npm si può lanciare lo stesso comando e se è windows fargli fare il comando unix like e se windows lanciare il mio

**Comment by Cadienvan** [comment]
@Il-Libro-Open-Source/tech-group questa cosa era già capitata internamente, lascio a voi l'eventuale decisione di implementare un automatismo piuttosto che informare gli utenti nel CONTRIBUTING.
