### ISSUE TITLE
Come vengono creati i branch

### ISSUE THREAD

**Issue by Livio74** [Il-Libro-Open-Source/book#175]
Ciao a tutti,

una delle domande ad esempio è come vengono creati i branch , mi sembrava di aver visto un documento apposta ma non lo trovo

Livio

**Comment by eppak** [comment]
Ciao @li, crei una issue partendo da uno degli argomenti, te la assegni e in automatico viene creato il ramo, poi fai una pull lì.

Fammi sapere.

**Comment by Cadienvan** [comment]
@eppak questo vale solo se sei un membro dell'org del libro, quindi ambassador o contributor.
Altrimenti devi attendere, appunto, che uno di loro lo faccia.

Altrimenti puoi proporre direttamente una PR se è un contenuto che non riguarda direttamente il libro o non è un contributo, ma più un suggerimento o una modifica rapida.

**Comment by eppak** [comment]
@Cadienvan grazie della precisazione!

Quindi posso eventualmente creare io e supportarlo se serve giusto? Se serve sono qui.

**Comment by Cadienvan** [comment]
Crearlo può farlo lui, assegnarlo e creare il branch deve essere uno del team.

**Comment by Cadienvan** [comment]
Ciao @Livio74 ,
se reputi che la risposta alla tua domanda sia soddisfacente possiamo chiudere questa issue, se invece hai ancora dei dubbi dicci quali sono e ti risponderemo!

**Comment by Livio74** [comment]
> Ciao @Li, crei una issue partendo da uno degli argomenti, te la assegni e in automatico viene creato il ramo, poi fai una pull lì.
> 
> Fammi sapere.

Puoi chiudere , dovrebbe essere questa la risposta

**Comment by Cadienvan** [comment]
Attenzione che Alessandro, come scrivevo in risposta, ha ipotizzato tu fossi un Ambassador.
In realtà chi contribuisce come contributor fuori dall'organizzazione può aprire una issue o forkare e proporre una PR a un branch o a main, come in un qualsiasi progetto Open Source.
