### ISSUE TITLE
Lancio dicembre 2023 npm run format:check restituisce alcuni warning

### ISSUE THREAD

**Issue by Livio74** [Il-Libro-Open-Source/book#179]
Di seguito l'elenco:
Checking formatting...
[warn] .github/ISSUE_TEMPLATE/patch-chapter.md
[warn] .github/ISSUE_TEMPLATE/post-chapter.md
[warn] AMBASSADORS.md
[warn] CODE_OF_CONDUCT.md
[warn] CONTRIBUTING.md
[warn] docs/index.md
[warn] docs/it/cosa-significa-essere-dev.md
[warn] docs/it/introduzione.md
[warn] GUIDELINES-CHEATSHEET.md
[warn] GUIDELINES-CONTENUTI.md
[warn] GUIDELINES.md
[warn] LICENSE.md
[warn] notes/README.md
[warn] README.md
[warn] Code style issues found in 14 files. Run Prettier to fix.

**Comment by Cadienvan** [comment]
![Screenshot 2023-12-02 alle 18 12 51](https://github.com/Il-Libro-Open-Source/book/assets/5492927/ffffb4fd-f0a2-4a43-a31c-d08f86e94e1d)
Ciao @Livio74 , posso chiederti se hai per caso qualche altro output dalla console? Ho provato a lanciare localmente lo stesso comando ma non riscontro il problema che mi segnali.

**Comment by Livio74** [comment]
E' un falso positivo , quando si scaricano i file su windows con GIT lui mette i ritorni accapo di Windows.
Magari si può dire a GIT scaricare i file utilizzando sempre i ritorni accapo di UNIX

**Comment by Livio74** [comment]
forse si riesce utilizzando il file .gitattributes

**Comment by Cadienvan** [comment]
Qui parliamo di una impostazione di Git però.
@eppak può avere senso indicarlo nelle FAQ, in ogni casonon si tratta di un bug sul repo, quanto più di una differente configurazione del proprio Git locale.

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings magari questo aiuta?

**Comment by Cadienvan** [comment]
Ciao @Livio74 ,
questa si è risolta con le tue PR, vero?

**Comment by Livio74** [comment]
Ciao @Cadienvan , si chiudi pure grazie
