### ISSUE TITLE
su windows non riesco a committare per gli hooks

### ISSUE THREAD

**Issue by Livio74** [Il-Libro-Open-Source/book#180]
Penso che sia commitlint non mi fa committare.
Per me sarebbe utile poterlo lanciare anche come se fosse lo stesso comando che viene lanciato come hook del commit per correggere eventuali problemi

**Comment by Cadienvan** [comment]
Possiamo chiederti dei log?
Cosa intendi per "non riesco a committare"?

**Comment by Livio74** [comment]
Di seguito la schermata:
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.5.0  hook: commit-msg │
╰──────────────────────────────────────╯
┃  commitlint.sh ❯

⧗   input: aggiunta git Attributes per cambiare ritorno accapo in unix like
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint


exit status 1
  ────────────────────────────────────
summary: (done in 15.10 seconds)
🥊  commitlint.sh

**Comment by Livio74** [comment]
purtroppo non mi dice quali sono i problemi riscontrati

**Comment by Cadienvan** [comment]
Ciao @Livio74 ,
confermo che usiamo i conventional commit come indicato nel file [CONTRIBUTING](https://github.com/Il-Libro-Open-Source/book/blob/main/CONTRIBUTING.md).

Chiudo, menomale che era solo questo ;)
