### ISSUE TITLE
sistemazione fine riga unix like su git e su prettier su tutti i branch

### ISSUE THREAD

**Issue by Livio74** [Il-Libro-Open-Source/book#186]
In riferimento alla pull request numero 185 come da oggetto ,  sarebbe da integrare questa modifica dei file .gitattributes e .prettierrc su tutti i branch.
A suo tempo avevo inserito solo la modifica del primo file sul main quindi in questo è sufficiente aggiungere il file .prettierrc , se volete lo faccio io

**Comment by Cadienvan** [comment]
Ciao @Livio74 ,
in realtà la #185 è superflua, sarà sufficiente allineare il branch di formazione a main così si porta indietro le modifiche.

Ho fatto rebase del branch, chiudo questa issue e la PR, non è più necessario :)

Dal tuo fork ti basterà fare un pull oppure un rebase, se hai bisogno chiedi pure!
