### ISSUE TITLE
[🆕]: Ciclo del feedback

### ISSUE THREAD

**Issue by Jean85** [Il-Libro-Open-Source/book#210]
# 🆕 Nuovo capitolo - Ciclo del feedback

## Descrizione
@Cadienvan [mi ha suggerito](https://github.com/Il-Libro-Open-Source/book/discussions/3#discussioncomment-8343506) di proporre questo contenuto come un nuovo capitolo.

Riporto quanto scritto nella discussione:

> [...] una parte abbastanza di alto livello, in cui sì sottolinea come l'avvento del settore IT e la cosiddetta "digital transformation" ha portato una accelerazione mostruosa nei ritmi di lavoro e di evoluzione dei processi, e che ci si è accorti che il "soft" in software ha una proprietà di malleabilità talmente forte che non sfruttarla è uno spreco. Da qui l'adozione delle varie pratiche (dal lean al continuous improvement, dal TDD alla CI) e come queste cose si trasformano in strumenti vitali nella vita di ogni giorno dello sviluppatore e, in modo più allargato, nella vita di qualunque azienda abbia un briciolo di reparto IT al suo interno.
>
> Visto che cita troppi argomenti, mi sembra una introduzione a capitoli successivi che poi potrebbero approfondire le varie tematiche. O, alternativamente, un capitolo "finale" di sintesi che raccorda questi temi per sottolineare il filone unico, quasi come una morale.

## Fonti

* https://martinfowler.com/bliki/TestDrivenDevelopment.html
* https://martinfowler.com/articles/continuousIntegration.html

**Comment by Cadienvan** [comment]
Ciao @Jean85 ,
attendo eventuali altri @Il-Libro-Open-Source/ambassadors che vogliano prendere il mio posto in questo compito, ma se in linea generale potresti essere interessato, come dicevamo nella discussion, a stendere una prima versione del contenuto, io mi rendo disponibile a farti da ambassador accompagnatore, che ne pensi?

L'idea è che tu possa pensare di buttare giù una table of content molto abbozzata di cosa vuoi dire e il tono che vuoi dare al capitolo e poi ci prendiamo 20-30 minuti assieme per capire un po' come iniziare, ti va?

**Comment by Cadienvan** [comment]
Potrebbe aver senso aggiungere una nota al SDLC (Systems development life cycle)?

**Comment by Jean85** [comment]
@Cadienvan ho buttato giù due righe in #212 giusto per fare un po' di "brain dump", fammi sapere come vuoi procedere!

**Comment by Cadienvan** [comment]
Ciao @Jean85 ,
ho commentato la PR.

Mi sono assegnato la issue, così ora puoi chiudere la tua PR e aprirne una verso quel branch.

Così facendo le review saranno isolate e non subirai gli stessi check necessari per la pubblicazione definitiva che avverrà a stesura completata :)
