### ISSUE TITLE
[✍️]: Modifica capitolo - TESTING

### ISSUE THREAD

**Issue by JarvisScienz** [Il-Libro-Open-Source/book#219]
# ✍️ Modifica capitolo - TESTING

## Descrizione

Trovo fuorviante l'inserimento del Test-driven development. Anche se chiaramente espresso nel capitolo che non si tratta di una metodologia di test, io lo rimuoverei da questo capitolo e lo inserirei in un capitolo dedicato alle metodologie di sviluppo.

**Comment by BrianAtzori** [comment]
Ciao @JarvisScienz, innanzitutto grazie della collaborazione! 

Questa Issue é un ottimo suggerimento effettivamente, attualmente però non vorremmo sottrarre contenuto da uno dei capitoli del libro, essendo di per se un concetto valido e comunque inerente al testing. 

Vorremmo proporti però di aprire un capitolo sulle metodologie di sviluppo, in modo da collaborare insieme ad uno degli Ambassadors alla stesura ed integrare la parte sul TDD segnalata da parte tua come da migrare, che ne dici? 

Se sei interessato possiamo procedere in questo modo, altrimenti se giustamente non vuoi partecipare all'effort di scrivere un nuovo capitolo o di contribuire ad una sua parte terremo conto di questa segnalazione per il futuro, in quanto al momento non abbiamo in stesura un capitolo sulle metodologie.

**Comment by JarvisScienz** [comment]
Ciao @BrianAtzori, si volentieri. Mi piacerebbe poter contribuire 😄

**Comment by Cadienvan** [comment]
Ciao @JarvisScienz ,
spettacolo!

Sarò ben contento (E credo che @BrianAtzori mi seguirebbe volentieri) di aiutarti nella stesura di questo eventuale capitolo, nel caso apri pure una nuova issue proprio come fatto con questa, però di creazione nuovo capitolo, e attendi che almeno un ambassador se la assegni ;)

Al momento questa la chiudo, in quanto finché non portiamo dentro l'eventuale nuovo capitolo, come giustamente accennava Brian, non sarebbe plausibile togliere del contenuto!

**Comment by BrianAtzori** [comment]
Ciao @JarvisScienz, confermo e sottoscrivo quando detto da Michael! 
Anzi ci tengo a scusarmi per la latitanza, avevo visto la notifica ma in questi giorni non avevo spazio per darti un riscontro, fiducioso che qualcun'altro ti avrebbe dato una risposta, ho visto che è stata aperta la issue e come anticipato sempre dal buon Michael sarò ben felice di darti una mano, al momento sto lavorando ad un altro capitolo ma il bello di questo progetto è proprio la collaborazione 🤝
