### ISSUE TITLE
[🆕]: Domain Driven Design

### ISSUE THREAD

**Issue by baldarn** [Il-Libro-Open-Source/book#226]
# 🆕 Nuovo capitolo - Domain Driven Design

## Descrizione

Una introduzione al [DDD](https://en.wikipedia.org/wiki/Domain-driven_design) (domain driven design), metodologia di sviluppo molto interessante per team medi/grandi

## Fonti

[Learning Domain-Driven Design](https://www.oreilly.com/library/view/learning-domain-driven-design/9781098100124/)

**Comment by Cadienvan** [comment]
Ciao @baldarn , benvenuto a bordo!!

Mi sembra un capitolo bello tosto ma che sicuramente mi piacerebbe leggere se entrassi oggi nel mondo informatico!

Vedo dalla PR in draft che hai aperto che hai già avuto modo di leggere la documentazione su come contribuire e sei partito lanciato, mi piace!

Sarei contento, qualora qualcun altro non preferisse farlo al posto mio, di farti da Ambassador accompagnatore per questo capitolo.

Hai già in mente una scaletta di contenuti o un modo con cui trattare il tema?

Nel caso potessi esserti d'aiuto, aggiungimi pure su LinkedIn e facciamoci due chiacchiere!
