### ISSUE TITLE
Titolo fuorviante

### ISSUE THREAD

**Issue by garak** [Il-Libro-Open-Source/book#233]
Vedo che nelle issue chiuse c'è già stata una discussione sul titolo, ma qui vorrei evidenziare un problema collaterale.

Sono arrivato a questo repo vedendo su Linkedin la semplice dicitura "Il libro open source" e poi trovandomi di fronte una bella immagine di una libreria a scaffali con al centro la scritta a caratteri grandi "OPEN SOURCE".

Ora io, fino a qui, ero convinto di trovare dei contenuti il cui tema principale fosse il mondo dell' open source, mentre a un certo punto ho trovato, scritto abbastanza piccolo "Manuel del buon dev". Il che va benone, per carità, ma forse sarebbe il caso di farlo capire un po' prima.

Se posso dare un suggerimento: bisognerebbe mettere più in risalto il sottotitolo, sia nella parte testuale sia nella parte visiva.

**Comment by Cadienvan** [comment]
Ciao @garak ,
il libro è nato secondo i principi dell'Open Source e solo in un secondo momento è diventato "Manuale del buon dev", quindi abbiamo ritenuto corretto che si chiamasse così e che continuasse ad essere questo.

Sono però d'accordo sul fatto che potremmo specificare diversamente il contenuto. Che suggerimenti avresti per farlo?

**Comment by Cadienvan** [comment]
Chiudo in quanto la situazione è già stata menzionata anche internamente. Riaprirò qualora ci fossero commenti e idee a riguardo, grazie!
