### ISSUE TITLE
Header troppo vicino alla viewport, rende il titolo poco leggibile

### ISSUE THREAD

**Issue by nicolaerario** [Il-Libro-Open-Source/book#236]
### Home > header

- L'header avrebbe bisogno di maggiore spazio, in modo da dare il giusto risalto al titolo;
- Inoltre, ora il titolo risulta troppo attaccato alla viewport

<img width="995" alt="Screenshot 2024-06-28 alle 15 37 03" src="https://github.com/Il-Libro-Open-Source/book/assets/37365465/caf650e2-89d2-4f95-8ff7-64ab78865ad0">

**Comment by Cadienvan** [comment]
@elgorditosalsero il nostro esperto di temi magari ci sa aiutare senza nemmeno guardare la doc!
