### ISSUE TITLE
[✍️]: Sviluppatore “senior”

### ISSUE THREAD

**Issue by GiovanniTosini** [Il-Libro-Open-Source/book#247]
# ✍️ Modifica capitolo - Sviluppatore “senior”

## Descrizione

Non è molto importante probabilmente, volevo segnalare un blocco di testo che poteva essere scritto differentemente

## Fonti

In questo punto:

> Immagina di disegnare una “T”. la linea verticale rappresenta una profonda conoscenza in una specifica area tecnica. Più questa linea è lunga più si è raggiunta una padronanza della specifica area tecnica. Invece, la linea orizzontale rappresenta una vasta conoscenza in tante altre aree, non necessariamente una conoscenza approfondita ma sufficiente sviluppata da fornire i mezzi per poter spaziare tra gli argomenti piú disparati durante una conversazione tecnica.

segnalo due cose:
- dopo 
> Immagina di disegnare una “T”
 
metterei una virgola
- > una conoscenza approfondita ma sufficiente sviluppata da fornire i mezzi

metterei cambierei 'sufficiente' con 'sufficientemente'

- 
> Ovviamente è meglio preferire delle aree tecniche per le quale ci si senta particolarmente

'per le quale' > per le quali

**Comment by GiovanniTosini** [comment]
Ciao @Cadienvan, ho aperto la PR spero di aver fatto tutto come si deve

**Comment by Cadienvan** [comment]
Hai fatto tutto alla perfezione, grazie!

Ti aspettiamo per un futuro contributo!!

**Comment by GiovanniTosini** [comment]
È stato un piacere poter contribuire un pochino!

Il sab 5 ott 2024, 18:18 Michael Di Prisco ***@***.***> ha
scritto:
