### ISSUE TITLE
Prettier per Markdown

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#31]
Come suggerito da [nicolaerario](https://github.com/nicolaerario) sarebbe interessante implementare un linting con Prettier per i markdown.
Rules da definire, ma perlomeno potremmo partire con la configurazione.

Tengo aperta questa issue per chiunque voglia buttarcisi, altrimenti ci penserò io ;)

**Comment by Balastrong** [comment]
Sto pensando se c'è un modo per assicurarci che le modifiche pushate siano già formattate, ma se il progetto è solamente dei file .md non mi viene in mente niente che funzioni in automatico al 100%

Un piano B può essere una combo di github action per verificare che nelle PR sia tutto formattato + due righe di documentazione su come installare prettier nel proprio IDE preferito (o in un git hook)

**Comment by Cadienvan** [comment]
Ciao Leonardo, che bello aver ricevuto la tua notifica!

Sì, credo che una github action con un hook siano le indicazioni più vicine a ciò che ci serve..
E sì, due righe male non fanno!

**Comment by nicolaerario** [comment]
Espando brevemente il mio pensiero.
A me piace scrivere in markdown (_colpevole Vostro Onore_) e trovo Prettier sempre un fedele alleato per le mie scorribande  di formattazione. È `opinionated` e funziona bene (ha ragione lui e non si litiga per lo stile di formattazione). Fa il suo sporco lavoro anche coi miei `.md` e non sono mai andato a cercare se ci fosse magari un tool più specifico.
Aggiungo che gradisco la sua capacità di formattare (seguendo il linguaggio specifico) i blocchi di codice negli md.

![Screenshot 2023-08-09 alle 10 39 52](https://github.com/Il-Libro-Open-Source/book/assets/37365465/ef13bad8-16c5-4ac0-9e11-8d17676ecda4)


Detto questo, consiglierei come configurazione, di sovrascrivere solo il `printWidth`: io normalmente lo porto a 100 (80 lo capisco ma mi piace fare il birichino certe volte)

```
{
  "printWidth": 100
}
```

Per quanto riguarda l'integrazione e la consistenza di cui parla @Balastrong , ci ragiono su un attimo. Stay tuned

**Comment by nicolaerario** [comment]
Grazie @Balastrong per la PR.

Stavo ragionando un attimo sul flow di contribuzione:
Parto dalla forma più elementare di contribuzione, cioè il fork e la modifica di un file direttamente da GH;
Se questa sarà accettata (e credo di si), non si può fare affidamento sull'accuratezza del Contributor (CLI, plugin, git-hooks, ecc);
La contribuzione dovrà necessariamente essere revisionata e finalizzata internamente, secondo me.

Ottima la action che performa un `check`, mi chiedevo se potesse essere utile un `write & commit`.

**Comment by Balastrong** [comment]
Sicuramente una action che fa write e commit è un ottimo strumento per risparmiare tempo, ragionerei un attimo su quando farla girare.

Immagino il caso in cui è al classico push sulle PR, c'è la situazione in cui pushi un commit, la action ne mette un altro che formatta ma dimentichi di fare pull. Dopo un po' cerchi di pushare un altro commit e magari trovi dei conflitti.
PRO nella maggior parte dei casi ti aiuta in automatico
CONTRO in alcuni casi potrebbe avere dei side effect scomodi

Altra opzione è lanciare a mano l'action che fa anche commit (con [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)) solo quando serve
PRO nessun side-effect indesiderato e può essere usata anche da chi lavora da GH (nel proprio repo immagino)
CONTRO anche se sono letteralmente due click, va fatto a mano

La butto lì come spunto di discussione, non ho un'opinione forte al riguardo :)

**Comment by nicolaerario** [comment]
Potrebbe essere una action "finale" quando si va da `dev` a `release` per esempio.

**Comment by Balastrong** [comment]
Non so se forse è troppo tardi, nel frattempo mentre è su `dev` potrebbero esserci più PR sullo stesso file e comunque mi aspetterei sia già formattato quando creo un nuovo "feature" branch 🤔

(ammesso che avremo un flusso a più branch per le release piuttosto che dei semplici tag)

**Comment by nicolaerario** [comment]
> Non so se forse è troppo tardi...
Effettivamente in questo punto sarebbe più un check di sicurezza;

Io direi che puoi referenziare questa issue nella PR in modo che venga chiusa al merge.

Continuiamo (secondo me) ad elaborare magari in una discussione apposita e ci ritorniamo più agguerriti una volta che saranno definiti altri aspetti del repo, che ne pensi @Cadienvan ?

di nuovo grazie @Balastrong

**Comment by Cadienvan** [comment]
Direi proprio di sì, sono tutte cose da prendere con le pinze per rendere l'esperienza semplice per tutti..

@nicolaerario hai ragione quando dici che dovremmo accettare PR direttamente da Github, alla fin fine molti contribuiranno fixando typo o aggiungendo via via poche cose, quindi è molto sensato..
@Balastrong credo che il dispatch di una action sia la cosa migliore per quanto messo sul piatto finora, anche se appunto non è risolutivo..

Magari entrambe le cose? Non so, parliamone.

**Comment by Balastrong** [comment]
Intanto potremmo mettere in pratica una soluzione abbastanza leggera, tanto non sappiamo l'entità del problema (quanto spesso ci sarà da formattare pr a mano).
Alla peggio a fare checkout di una pr, formattare e rifare commit ci vuole letteralmente un minuto (spam: [come fare review di una pr da vscode](https://youtu.be/DSl-L6B_Qb4), basta che un maintainer preme due bottoni da vscode ed è fatta)

Poi quando capiamo effettivamente quel è il problema che porta via più tempo o che causa più frizione ai contributor, risolviamo direttamente quello :D

**Comment by Cadienvan** [comment]
SPAM SPAM!
Ci sto.

**Comment by Cadienvan** [comment]
Sarebbe un'idea molto interessante, sì.

Main per le "release", che saranno seguite da appositi tag, e poi un branch "dev" in cui far convergere la versione "beta", ci potrebbe stare eccome.

Per quanto riguarda l'esposizione dei contenuti io punto su Docusaurus perché ha una esposizione e una flessibilità ben note, oltre che una buona stabilità, ma credo che la cosa migliore, come già suggerivi, @JeyDi , sia aprire una issue a riguardo così da permettere uno scambio di opinioni più verticalizzato su questo tema.

@nicolaerario o @JeyDi , direi che poco cambia chi di voi apra la issue, che lo faccia uno di voi così possiamo parlarne!
