### ISSUE TITLE
Setup GitHub pages to host and publish online the book

### ISSUE THREAD

**Issue by nicolaerario** [Il-Libro-Open-Source/book#35]
Users will be able to read the book online, thanks to GitHub pages

Related to [this comment](https://github.com/Il-Libro-Open-Source/book/discussions/27#discussioncomment-6699310) and to the comments in #31

**Comment by JeyDi** [comment]
Hi guys! If you agree I would like to start setup docusaurus to have the first version online, and then little by little we can work on the optimisation and graphics.
I found some good example on what we can achieve with Docusaurus, here some links:
- https://handbook.infinityworks.com/culture/cops
- https://www.frontendinterviewhandbook.com/introduction/
- https://www.techinterviewhandbook.org/software-engineering-interview-guide/

Here the link to the [Docusaurus tutorial](https://tutorial.docusaurus.io/docs/intro)

**Comment by Cadienvan** [comment]
Both the ideas are fantastic, keep them in your pocket for September!

**Comment by nicolaerario** [comment]
I think we can start lean with GH Pages: it's literally 1 setting (pages activation) and 1 select (what branch and folder watch for the builds).
I suggest to use the standard `docs` folder with the index of the book as entry point.
In the future, and with greater awareness, we may migrate to more advanced solutions (if they are needed)

**Comment by corradopetrelli** [comment]
I totally agree with @nicolaerario. Now we need a simple tool for publishing that can make us shift focus only to the contents to be written.

**Comment by Cadienvan** [comment]
I agree.
@nicolaerario do you need anything done on my side?
Today I'm bringing in all the stuff discussed yesterday so I'm a little off-topic now, but ask me, and it'll be done ;)

**Comment by nicolaerario** [comment]
@Cadienvan I'll make the scaffold, then the PR. I'll tell you exactly what you need to enable
