### ISSUE TITLE
Errore nel README

### ISSUE THREAD

**Issue by garak** [Il-Libro-Open-Source/book#44]
Questa frase è sbagliata:

>hanno deciso di contribuire al progetto in maniera diretta, prendendosi la responsabilità di uno o più capitoli, piuttosto che di altre aree

La frase corretta è:

>hanno deciso di contribuire al progetto in maniera diretta, prendendosi la responsabilità di uno o più capitoli, oppure di altre aree

Nel caso, posso proporre una PR.

**Comment by Cadienvan** [comment]
Vai di PR!

**Comment by Cadienvan** [comment]
@garak ho visto che hai fatto un fork ma non hai ancora fatto la PR, se ce la richiedi la accettiamo volentieri!

**Comment by garak** [comment]
> @garak ho visto che hai fatto un fork ma non hai ancora fatto la PR, se ce la richiedi la accettiamo volentieri!

Chiedo venia, per far prima son passato dall'interfaccia di github, che non uso molto spesso. Credevo di aver completato la procedura ma evidentemente mi son perso un pezzo per strada... aperta PR ora.
