### ISSUE TITLE
Choice of a comfortable branching model

### ISSUE THREAD

**Issue by nicolaerario** [Il-Libro-Open-Source/book#53]
My thinking is to keep the work simpler: one or, at most, two _long life_ branches.
I don't think we'll need to do hotfixes in production... Releases could be managed through tags and related assets.

**Comment by guizzo** [comment]
Makes sense to me, that's fine 👍

**Comment by corradopetrelli** [comment]
Something like that?

```mermaid
gitGraph
    commit
    commit
    branch publishable
    checkout publishable
    commit
    branch topic1
    commit
    checkout publishable
    branch topic2
    commit
    checkout publishable
    branch topic3
    commit
    commit
    commit
    checkout topic2
    commit
    commit
    checkout topic1
    commit
    commit
    checkout publishable
    merge topic1
    merge topic2
    merge topic3
    checkout main
    merge publishable tag: "v0.1.0"
```

**Comment by Cadienvan** [comment]
I like @corradopetrelli idea, a branch for every topic and a main + publishable configuration.
This will need a great explanation tbh, as many new contributors could have a hard time understanding how to fork the correct branch.

**Comment by Cadienvan** [comment]
Let's wait for the others but I like this idea.

**Comment by corradopetrelli** [comment]
> In case it goes on, do you wanna get responsibility for it?

Since in my opinion it's an urgent matter, it's better for me not to take responsibility for it since I'm going on holiday next week 🥲

**Comment by Cadienvan** [comment]
Ok I'll try to arrange something in the following days

**Comment by nicolaerario** [comment]
Sorry to be repetitive, but I think we can start with something simple (as we are already doing):
[github-flow](https://docs.github.com/en/get-started/quickstart/github-flow).

We can always improve later.

**Comment by Cadienvan** [comment]
@nicolaerario is this what you mean?
Just to make it easier for everybody to follow.
```mermaid
gitGraph
    commit
    commit
    branch topic1
    commit
    checkout main
    branch topic2
    commit
    checkout main
    branch topic3
    commit
    commit
    commit
    checkout topic2
    commit
    commit
    checkout topic1
    commit
    commit
    checkout main
    merge topic1
    merge topic2
    merge topic3
```

**Comment by nicolaerario** [comment]
I recommend reading [this](https://nicolaerario.github.io/fake-it-till-you-make-git/docs/en/issue-pr-branch.html), even just the TLDR

**Comment by Cadienvan** [comment]
@nicolaerario quindi direi che è un Github Flow alla fin fine, o sbaglio?

**Comment by nicolaerario** [comment]
> @nicolaerario quindi direi che è un Github Flow alla fin fine, o sbaglio?

Diciamo di si. Leggermente migliorato perché nel mio giro si parte prima da una "ricerca della issue" e dal fatto di consegnare sempre "materiale nuovo ed aggiornato".

**Comment by Cadienvan** [comment]
Quello senza dubbio e voglio dare un occhio fino alla fine dell'articolo in sti giorni.

**Comment by Cadienvan** [comment]
Il Tech Group é ora formato, di conseguenza dopo il voto degli Ambassador sul branching model da adottare, chiudo questa issue.
