### ISSUE TITLE
Using italian language instead of english to low the entry barrier

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#54]
As discussed on telegram, @akelity proposed to switch to the italian language for all the communications.
As mentioned by @nicolaerario, we grew a lot in the past few weeks so I guess we could re-think about that.

Any opinions @Il-Libro-Open-Source/ambassadors ?

**Comment by serenasensini** [comment]
Totally agree... Ops, volevo dire: AVOJA! 🔥

**Comment by guizzo** [comment]
Do i miei due centesimi al riguardo:

considerando quanto scarso sia il mio inglese, nel quotidiano preferisco lavorare in Inglese, quantomeno per "provare" a tenermi allenato.

Per quanto riguarda questo progetto però, avendo esso come obiettivo quello di abbattere quanti più scogli possibili e rendere "accessibile" le informazioni in esso contenute a tutti, penso che sia più sensato  lavorare in Italiano.

**Comment by GuidoPenta** [comment]
Sono d'accordo con @guizzo : per renderlo accessibile dovrebbe essere tutto in italiano.
A tradurlo poi in inglese si fa sempre in tempo!

**Comment by nicolaerario** [comment]
La discussione non era nata riguardo al fatto della traduzione o meno in inglese, bensì sul mantenere la `history` in inglese: cosa che io comunque continuo a sostenere.
Ecco la discussione originale
https://github.com/Il-Libro-Open-Source/book/discussions/27#discussioncomment-6739336

**Comment by GuidoPenta** [comment]
Hai la mia spada, allora.

**Comment by guizzo** [comment]
> La discussione non era nata riguardo al fatto della traduzione o meno in inglese, bensì sul mantenere la `history` in inglese: cosa che io comunque continuo a sostenere. Ecco la discussione originale [#27 (comment)](https://github.com/Il-Libro-Open-Source/book/discussions/27#discussioncomment-6739336)

Per la `history` sono d'accordo, ma le varie issue ed i relativi commenti li lavorerei comunque in Italiano; un domani potrebbero comunque tornare utili a chi vorrà prenderà parte al progetto per contribuire ma ha difficoltà con l'Inglese

**Comment by Cadienvan** [comment]
Quindi la proposta da parte di voi 3 è: Tutto italiano, ma commit e relativo "changelog" o "history" in inglese?

**Comment by elgorditosalsero** [comment]
Io approvo quanto dice @nicolaerario

**Comment by eppak** [comment]
Anche io voto per l'italiano, per i commit mo adeguo anche se mi suonerebbe strano doverli mixare nel messaggio es. "feat: added new chapter cosa é un senior Dev"

**Comment by nicolaerario** [comment]
> Anche io voto per l'italiano, per i commit mi adeguo anche se mi suonerebbe strano doverli mixare nel messaggio es. "feat: added new chapter cosa é un senior Dev"

So che è un esempio il tuo @eppak
Non me ne vogliate tutti se approfitto a fare pubblicità:

[Why your history is like a fix...fax...fox?](https://nicolaerario.github.io/fake-it-till-you-make-git/docs/en/conventional-commits.html)

**Comment by sensorario** [comment]
Per me ha senso comunicare con la stessa lingua con cui verra scritto il libro.

**Comment by passasooz** [comment]
Per i commit potremmo usare i conventional commit, ma tutto il resto (anche le issue) teniamoci l'italiano

**Comment by AngeloAvv** [comment]
Anch'io sposo l'Italiano. Le riflessioni fatte in determinati capitoli avranno come target per forza di cose il pubblico Italiano. Per i commit invece mi è indifferente

**Comment by JeyDi** [comment]
L'italiano può essere un limite, però visto anche il nome dell'organizzazione e i partecipanti sono d'accordo con voi nel tenere tutto in Italiano nella prima versione :)

Facciamo sempre in tempo a tradurre quando abbiamo un po' di contenuti..inoltre è bello che sia un contenuto dedicato alla community Italiana siccome ci lamentiamo sempre che c'è poca letteratura tradotta :)

**Comment by Cadienvan** [comment]
Sembra che siamo tutti d'accordo.

Reputo sufficiente rispettare i conventional commits anche se bisognerà vedere come va.. Per me saranno 800.000 chore ahah

Rimane il nodo sulla history, ovvero se tenere i commit in italiano o in inglese. Suggerirei, visto che si pensa di tenere come UNICA cosa i commit in inglese, che tanto vale farli in italiano così uno non si confonde.

Credo sia sufficiente un sondaggio su Telegram a questo punto.

**Comment by eppak** [comment]
Teniamo l'italiano anche per issue e discussioni?
