### ISSUE TITLE
Moving all the meeting notes and discussions in a separate repository

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#55]
A Github organization allows us to have many different repositories so that we can stay clean and organized.

My suggestion is to move all the meeting notes and the official maintained list of ambassadors with start and end dates in a different repository, something like a "governance" repository.

What do you all think? @Il-Libro-Open-Source/ambassadors

**Comment by davideimola** [comment]
Yes, absolutely.
I suggest creating a Community repo, which may contain the CODE OF CONDUCT, RULES, AMBASSADOR, and meeting notes!

**Comment by JeyDi** [comment]
I agree with you, but be careful not to spread your energies too thin...in the end you risk having lots of repositories, lots of scattered material, and very disorganized discussions...

At the moment I don't think there is a need to do this, maybe it could be left at a later time when we agree that it has all become too difficult to manage? And focus on the content in the meantime?

**Comment by Cadienvan** [comment]
I'd just want to move the meeting notes in an ambassador-related repo, without moving all the rules etc..
Just ambassador names and meeting notes. What do you think @JeyDi ?

And then, if we find it manageable and useful, we can go with @davideimola suggestion.

**Comment by Cadienvan** [comment]
Chiudo avendo appena creato il [repository di governance](https://github.com/Il-Libro-Open-Source/governance)
