### ISSUE TITLE
Make the Repository collaboration-ready

### ISSUE THREAD

**Issue by nicolaerario** [Il-Libro-Open-Source/book#56]
Direttamente dalla discussione #23 

Naturalmente la lista cerca di essere esaustiva ma non tutti i punti potrebbero servire nel concreto. Se c'è qualcosa che manca invece...

### 1. Repository Settings

- [x]  set appropriate repository visibility (public or private)
- [x]  configure branch protection rules

### 2. Repository Contents

- [x]  create an informative README.md
- [ ]  add a LICENSE.md file
- [x]  include CONTRIBUTING.md
- [ ]  set up CODEOWNERS
- [x]  establish a CODE_OF_CONDUCT.md

### 3. Automation/Checks

- [x]  implement code linting / formatting
- [ ]  set up tests / Continuous Integration (CI)
- [ ]  configure status checks
- [ ]  set up Continuous Deployment (CD)

### 4. Security

- [ ]  assign appropriate roles / permissions
- [ ]  manage secrets securely
- [ ]  set up scanners for dependencies, secrets, general vulnerabilities
- [ ]  setup Dependabot version updates
- [ ]  provide a SECURITY.md

### 5. Advanced Options

- [x]  add Issue Templates
- [ ]  define Environments

### 6. Next Steps / Externalities

- [ ]  commit to being responsive
- [ ]  use GitHub Projects and Issues for project management
- [x]  promote the project for visibility
- [x]  engage with the community

**Comment by guizzo** [comment]
`configure branch protection rules` lo farei ASAP

**Comment by nicolaerario** [comment]
quello era da consegnare "per ieri" in realtà

**Comment by Cadienvan** [comment]
[screencapture-github-Il-Libro-Open-Source-book-settings-branch-protection-rules-new-2023-09-14-11_13_22.pdf](https://github.com/Il-Libro-Open-Source/book/files/12607041/screencapture-github-Il-Libro-Open-Source-book-settings-branch-protection-rules-new-2023-09-14-11_13_22.pdf)
There you go. Ho cominciato con questi, ditemi che ne pensate, perlomeno è protetto.

**Comment by guizzo** [comment]
> [screencapture-github-Il-Libro-Open-Source-book-settings-branch-protection-rules-new-2023-09-14-11_13_22.pdf](https://github.com/Il-Libro-Open-Source/book/files/12607041/screencapture-github-Il-Libro-Open-Source-book-settings-branch-protection-rules-new-2023-09-14-11_13_22.pdf) There you go. Ho cominciato con questi, ditemi che ne pensate, perlomeno è protetto.

Così a naso alzerei `Required number of approvals before merging` a 5..che dite?

**Comment by Cadienvan** [comment]
Non ho messo i signed solo perché non tutti li usano, anche se sono d'accordo che dovrebbero..

**Comment by nicolaerario** [comment]
Secondo me `Branch name pattern` settato così è sbagliato: ora ci va semplicemente `main`.

Nota: `Require status check to pass...` potrebbe darci rogne in quanto la action attualmente usa npx (latest version) e non ha settings. Questo lo dobbiamo sistemare. Low priority

`Require branches to be updated...` potremmo pensarci in un secondo momento: attualmente mi affiderei sul fattore umano

`Require linear history` partirei off

`Lock branch` off

`Do not allow bypass` off (qui mi darete ragione poi)

cc @Cadienvan

**Comment by Cadienvan** [comment]
@nicolaerario il branch name l'ho messo sbagliato apposta così per ora non influisce.
Per il Lock branch come mai off?

**Comment by nicolaerario** [comment]
Ci avevo pensato al nome sbagliato di proposito, ma giacché scrivevo...

Avere il branch `read only` non credo serva, no? Le altre protezioni adottate sono più che sufficienti. Avoja 😎

**Comment by Cadienvan** [comment]
Ma così non rischiamo che uno di noi possa pushare su main? O mi sono perso un altro blocco?

**Comment by nicolaerario** [comment]
> Ma così non rischiamo che uno di noi possa pushare su main? O mi sono perso un altro blocco?

Diciamo che il lock serve per metterlo in manutenzione: nessuno ci può fare nulla, nada nisba. È congelato. Credo che i fork nemmno possano syncare (ma forse hanno cambiato sta cosa)

Se vuoi pushare su main puoi (e devi) farlo solo tramite PR.
Se le PR sono obbligatorie, richiedono approvals, non c'è force push, non c'è deletions... siamo abbastanza blindati E possiamo lavorare col branch.

È `Il libro open source` mica `Il libro di Alcatraz` 🤣

**Comment by nicolaerario** [comment]
Al massimo `Do not allow bypass` on se non ti fidi manco di te stesso. Ma, secondo me, uno coi `permessi di root` serve

**Comment by nicolaerario** [comment]
Vista l'evoluzione in issue, ho risolto la discussione originaria. grazie

**Comment by Cadienvan** [comment]
promote the project for visibility
 engage with the community

Mi sa che li possiamo segnare come fatti, che dici?

**Comment by nicolaerario** [comment]
> promote the project for visibility engage with the community
> 
> Mi sa che li possiamo segnare come fatti, che dici?

Fai pure come fosse il tuo repo 🤓

**Comment by Cadienvan** [comment]
- Giusti i primi 2 punti!
- Sulla licenza stiamo attendendo l'ingresso dei nuovi Ambassador tra cui c'è gente interessata all'argomento.
- Sui CODEOWNERS abbiamo lasciato l'argomento in sospeso sotto suggerimento del tech group, sì.

**Comment by corradopetrelli** [comment]
✅  add Issue Templates

**Comment by Cadienvan** [comment]
Ciao @nicolaerario @corradopetrelli e in generale tutto il team @Il-Libro-Open-Source/ambassadors , che ne dite se questa la chiudiamo? Direi che siamo sulla buona strada ora!

**Comment by corradopetrelli** [comment]
Per me va bene, siamo arrivati ad un punto minimal che ci rende collaboration-ready.
