### ISSUE TITLE
[🆕]: Cosa significa essere un dev

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#69]
Questa issue viene aperta per poter esprimere il proprio interesse verso l'argomento nel titolo.  

Chiunque sia interessato a questo argomento può mettere un 👍 su questa issue.  

Chiunque tra gli Ambassador sia interessato ad assegnarsi l'argomento per una prima versione può indicarlo in un commento o, più semplicemente, assegnare a se stesso la issue tramite l'interfaccia di GitHub.  

Chiunque sia interessato a contribuire può aggiungere un commento a questa issue.  

Chiunque sia interessato a proporre un argomento alternativo può farlo nella apposita [discussione](https://github.com/Il-Libro-Open-Source/book/discussions/3).

N.B. Non necessariamente l'argomento sarà trattato in un capitolo a sé stante. Potrebbe essere trattato in un capitolo più ampio o in un capitolo dedicato ad un argomento correlato. Questa issue viene aperta esclusivamente per valutare l'interesse nell'argomento.

**Comment by guizzo** [comment]
I'm in!

**Comment by passasooz** [comment]
interessa pure a me!

**Comment by Cadienvan** [comment]
Avete deciso di fare comunella voi due? Ahahahah la PR è già aperta, vai e contribuisci!
