### ISSUE TITLE
[🆕]: Version Control

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#76]
Questa issue viene aperta per poter esprimere il proprio interesse verso l'argomento nel titolo.  

Chiunque sia interessato a questo argomento può mettere un 👍 su questa issue.  

Chiunque tra gli Ambassador sia interessato ad assegnarsi l'argomento per una prima versione può indicarlo in un commento o, più semplicemente, assegnare a se stesso la issue tramite l'interfaccia di GitHub.  

Chiunque sia interessato a contribuire può aggiungere un commento a questa issue.  

Chiunque sia interessato a proporre un argomento alternativo può farlo nella apposita [discussione](https://github.com/Il-Libro-Open-Source/book/discussions/3).  

N.B. Non necessariamente l'argomento sarà trattato in un capitolo a sé stante. Potrebbe essere trattato in un capitolo più ampio o in un capitolo dedicato ad un argomento correlato. Questa issue viene aperta esclusivamente per valutare l'interesse nell'argomento.

**Comment by Livio74** [comment]
Su questo argomento posso contribuire illustrando alcune differenze fra SVN e GIT

**Comment by Cadienvan** [comment]
Ciao @Livio74 , la cosa migliore al momento è quella di buttare giù una table of contents, quindi diciamo i macro temi che vorresti trattare, che ne pensi?

**Comment by Livio74** [comment]
Ciao Michael , mi sembra una buona idea , proverò a fare un post con l'elenco

**Comment by Livio74** [comment]
Ciao a tutt*

Premessa importante , io conosco abbastanza bene GIT , benino SVN e pochissimo CVS e Source Safe quindi ne so solo una parte anche se penso dovremmo basare la maggior parte dell'argomento su GIT visto che è ampiamente utilizzato rispetto ad altri. Non conosco ad esempio Mercurial che so abbastanza utilizzato.
In realtà questa è più una bozza che andrebbe arricchita più che una versione definitiva quindi invito anche altri che sanno anche altri aspetti a contribuire.
Come promesso provo a fare una tabella dei contenuti per l'argomento Version Control.

Utilizzo dei sorgenti con cartelle condivise o simili e svantaggi
primo fra tutti la sovrascrittura dei file con accessi "contemporanei"

Definizione del controllo di gestione in particolare della traccia delle versioni dei file

Concetti e comandi di base
Repository , Init , checkout , update , lock file , commit , merge , rebase , cherry pick , branch , add , move , rename , remove , tags

utilizzo dei controllo di versione prima di git (CVS , Source safe , SVN , ecc)
accentramento del repository distinguendo server e client
In SVN ad esempio update scarica letteralmente da server e fa il merge mentre e il commit poi fa automaticamente il merge sul server

Git e differenze coi precendenti
Utilizzo di repository locale come se fosse remoto che permette di recuperare il repository semplicemente avendone solo uno
utilizzo di push e pull invece che update e commit diretto sul server

Ciao
Livio

**Comment by Cadienvan** [comment]
Ciao @Livio74 ,
mi sono appena accorto che ti ho lasciato "in sospeso" su questo tema.

Cosa ne pensi se proviamo a stenderlo insieme, magari sentendoci su LinkedIn per stabilire contenuti e forma? Potrei farti da ambassador per questo capitolo!

**Comment by Livio74** [comment]
Ciao @Cadienvan ,
certo ottima idea di farlo a quattro mani , risulterebbe decisamente fatto meglio che da solo , quando vuoi sentiamoci!

**Comment by Cadienvan** [comment]
Ciao @Livio74 ,
per il momento questa la chiudo in quanto a livello di Roadmap abbiamo un capitolo non in stesura da un bel po' di tempo, appena chiudiamo quello sui design pattern ben volentieri riaffrontiamo l'argomento!
