### ISSUE TITLE
[🆕]: Community / Networking

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#92]
Questa issue viene aperta per poter esprimere il proprio interesse verso l'argomento nel titolo.  

Chiunque sia interessato a questo argomento può mettere un 👍 su questa issue.  

Chiunque tra gli Ambassador sia interessato ad assegnarsi l'argomento per una prima versione può indicarlo in un commento o, più semplicemente, assegnare a se stesso la issue tramite l'interfaccia di GitHub.  

Chiunque sia interessato a contribuire può aggiungere un commento a questa issue.  

Chiunque sia interessato a proporre un argomento alternativo può farlo nella apposita [discussione](https://github.com/Il-Libro-Open-Source/book/discussions/3).  

N.B. Non necessariamente l'argomento sarà trattato in un capitolo a sé stante. Potrebbe essere trattato in un capitolo più ampio o in un capitolo dedicato ad un argomento correlato. Questa issue viene aperta esclusivamente per valutare l'interesse nell'argomento.

**Comment by davideimola** [comment]
@Cadienvan se hai bisogno di supporto su questo argomento, molto volentieri ti aiuto!

**Comment by Cadienvan** [comment]
Io assegno entrambi, sicuro si aggiunge anche il buon @akelity

**Comment by Cadienvan** [comment]
Prima di aprire la PR butto giù un po' di macro-temi che credo abbia senso trattare.

Pensavo di strutturare il capitolo in maniera un po' differente, ovvero una serie di domande e risposte. Cosa ne pensi @davideimola ?

Se non ti piace andiamo pure di stesura semplice, ma i temi che vorrei trattare comunque sono quelli che vedi sotto.

Buttati al volo:
- I dev sono veramente associali?
- Cosa vuol dire far parte di una community?
- Per la mia carriera è necessario / utile far parte di una community?
- Il networking ha senso quando sono all'inizio della mia carriera?
- Il networking ha senso quando sono senior?
- Come faccio networking sui social?
- Come faccio networking offline? <-- Qui probabilmente entriamo nell'argomento meetup quindi forse va più in #82 .

**Comment by davideimola** [comment]
Allora, direi che gli argomenti mi piacciono e sono tutti in tema! Penso che inevitabilmente il topic #82 e questo siano molto interconnessi e che si devano richiamare tra di loro spesso!

**Comment by Cadienvan** [comment]
@davideimola che ne pensi se rimuoviamo il punto che si incrocia con le conf e cominciamo a buttare giù qualcosa?
