### ISSUE TITLE
[🆕]: Annunci di lavoro

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#93]
Questa issue viene aperta per poter esprimere il proprio interesse verso l'argomento nel titolo.  

Chiunque sia interessato a questo argomento può mettere un 👍 su questa issue.  

Chiunque tra gli Ambassador sia interessato ad assegnarsi l'argomento per una prima versione può indicarlo in un commento o, più semplicemente, assegnare a se stesso la issue tramite l'interfaccia di GitHub.  

Chiunque sia interessato a contribuire può aggiungere un commento a questa issue.  

Chiunque sia interessato a proporre un argomento alternativo può farlo nella apposita [discussione](https://github.com/Il-Libro-Open-Source/book/discussions/3).  

N.B. Non necessariamente l'argomento sarà trattato in un capitolo a sé stante. Potrebbe essere trattato in un capitolo più ampio o in un capitolo dedicato ad un argomento correlato. Questa issue viene aperta esclusivamente per valutare l'interesse nell'argomento.

**Comment by Cadienvan** [comment]
@GuidoPenta faccio brainstorming con te.

Che ne pensi di trattare l'argomento indicando un tipico annuncio di lavoro "red flag" per parlare delle cose da considerare quando se ne guarda uno?

**Comment by GuidoPenta** [comment]
Molto interessante. Nella SPERANZA che poi questo libro venga letto anche da chi fa HR/Recruiting, si potrebbe ipotizzare di creare un annuncio "red flag" ed uno "green flag"

**Comment by sensorario** [comment]
Non so se sia il capitolo giusto ma pensavo a questo genere di messaggio da dare a chi cerca il primo lavoro. Iniziare può essere molto difficile. Il messaggio che vorrei trasmettere è di non mollare mai e di credere sempre a ciò che si desidera fare. Non pretendere di nascere programmatori ed aspettarsi di crescere, sempre. Per passare da una fase difficile dove il lavoro non si trova, fino ad arrivare ad una fase in cui è lo stesso lavoro che viene a cercarti. Che cosa ne pensate?

**Comment by Cadienvan** [comment]
A me l'idea di aggiungere una nota a riguardo piace. @GuidoPenta ? Che ne pensi se magari in ste settimane provo a buttare giù qualcosa a riguardo e mi accompagni?

**Comment by GuidoPenta** [comment]
Pensavo di integrarlo nel capitolo dedicato al CV e LinkedIn (magari una sezione dedicata a negoziazione, annunci di lavoro e temi dedicati).
Che ne dici?

**Comment by Cadienvan** [comment]
Ah perfetto, a questo punto direi che possiamo collegare questa issue a quel branch direttamente.
Allora guidi tu e io commento e integro nel caso, d'accordo?

**Comment by GuidoPenta** [comment]
Top!

**Comment by Cadienvan** [comment]
Chiudo visto che la leghiamo al capitolo già in stesura!
