### ISSUE TITLE
[🆕]: Smart Working / Remote Working / Ibrido

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/book#94]
Questa issue viene aperta per poter esprimere il proprio interesse verso l'argomento nel titolo.  

Chiunque sia interessato a questo argomento può mettere un 👍 su questa issue.  

Chiunque tra gli Ambassador sia interessato ad assegnarsi l'argomento per una prima versione può indicarlo in un commento o, più semplicemente, assegnare a se stesso la issue tramite l'interfaccia di GitHub.  

Chiunque sia interessato a contribuire può aggiungere un commento a questa issue.  

Chiunque sia interessato a proporre un argomento alternativo può farlo nella apposita [discussione](https://github.com/Il-Libro-Open-Source/book/discussions/3).  

N.B. Non necessariamente l'argomento sarà trattato in un capitolo a sé stante. Potrebbe essere trattato in un capitolo più ampio o in un capitolo dedicato ad un argomento correlato. Questa issue viene aperta esclusivamente per valutare l'interesse nell'argomento.

**Comment by guizzo** [comment]
I'm in!

**Comment by giuppidev** [comment]
@guizzo facciamo team nomade??

**Comment by guizzo** [comment]
> @guizzo facciamo team nomade??

Ciao @giuppidev 👋 

Sarò onesto: se c'è qualcuno qui che può parlare di nomadismo, quello sei tu 😄 

Io sono un semplice remote worker da circa 5 anni, nulla di più; mi sono proposto per l'argomento perché era uno di quelli ancora "orfani", e avendo questa esperienza sul remote working avevo pensato di buttare giù qualcosa al riguardo.

Ora che però ci sei tu, lascerei ben volentieri a te la guida, che ne sai a pacchi 💪 
Magari mi riservo la possibilità di avanzare proposte, qualora mi venissero in corso d'opera!

Che dici?

**Comment by giuppidev** [comment]
Ciao @guizzo! Ahahaha ma l'importante è essere nomadi nello spirito! 🚀

Comunque per me va bene tutto, anzi ne approfitto in questo spazio dedicato per chiederti come si procede.

Potrei iniziare a buttare giù qualcosa nel branch che è stato creato? Ci sono linee guida che non trovo a riguardo?

Ti ringrazio molto!

**Comment by BrianAtzori** [comment]
Ciao ragazzi! Se serve un a mano o posso contribuire anche io al contenuto relativo al lavoro da remoto, ora in modalità ibrida e precedentemente full remote!

**Comment by Cadienvan** [comment]
Ciao @giuppidev @BrianAtzori @guizzo avete  avuto modo di stendere qualcosa? Se serve una mano su approccio o linee guida sentiamoci volentieri!

**Comment by giuppidev** [comment]
@Cadienvan io ho iniziato a stendere qualcosina mettendo in ordine materiale sparso che ho sull'argomento.

Sono in questo momento in un treno notturno in Vietnam quindi sono giorni difficili 😂, ma settimana prossima posso rimettermi a tirare giù una prima bozza da condividere con tutti.

Nel frattempo condivido qui scaletta di massima per capire se può avere senso:

# Smart Working / Remote Working / Ibrido

## Cosa vuol dire lavorare da remoto?

## Telelavoro e storia del lavoro da remoto

## Diverse tipologie di remote working

## Smart working

## Remote working

## Ibrido

## La leggenda dei nomadi digitali

## Lavorare da remoto fa per tutti?

**Comment by Cadienvan** [comment]
Mi piace!!

@christiancannata ma che ne pensi di lavorare con Giuppi su questo?? No pressione, è che mi sembra una bella esperienza!
